### PR TITLE
Fixed incorrect key/values for Dungeon_Type

### PR DESCRIPTION
**Pull request by rohilthopu**
I have corrected the keys in the dungeon types (from what I can tell). The issue was that certain guerrilla and collab types I had labeled explicitly, rather than for what their broad categories were (i.e. gachadra and multiplayer collabs). The latter seems to have been arbitrarily labeled without realizing that all of them were just collab dungeons. As such, I've renamed what I had as dungeon_comment to what was previously dungeon_type, and my implementation of dungoen_type has been changed to dungeon category (as they are just broad descriptors).

One this is that some gachadra dungeons are marked as guerrilla and others as unknown-1, when generally I believe they are gift dungeons, however, this would just require the check for what was originally unknown-1 to be Gift (if there even is one, but afaik, this isnt necessary)

Give it a look when you get a chance. I'm fairly sure this corrects the remaining issues with guerrilla and collab dungeons.

### CODE REVIEW

**Comment by rohilthopu** [comment]
I readded the previous hack under an attr called bonus_type as certain dungeons, such as Gachadra's, are gift dungeons, but have a guerrilla prefix. I'm not sure how to handle those cases really. Might need to use bonus_type instead in padguide_processor.

**Comment by rohilthopu** [comment]
@nachoapps Just wanted to bring you back into this one if you have a chance. I've spent the last few days doing some testing and I believe these changes I made should fix all issues with dungeon types and let the now alt_dungeon_type be the official dungeon_type.

**Comment by dchang0413** [comment]
Gachadra dungeons are actually guerilla dungeons

**Comment by rohilthopu** [comment]
Correct. I had them specified as Gachadra rather than Guerrilla at first, which was why they were incorrect. I've changed that after comparing with the current set of Dungeons and Bonuses.

**Comment by rohilthopu** [comment]
Closing this one since it's getting kinda messy.

**Pull request closed without merging**
